### ISSUE TITLE
Some files won't download

### ISSUE THREAD

**Issue by C0rn3j** [Xerus2000/monsterutilities#49] opened 2019-06-20 07:40 UTC
I downloaded the entire monstercat library in FLAC (Single, Album, Monstercat Collection) and got 7 errors throughout, maybe there's some issue in parsing the song name or the cover just doesn't exist?

```
02:49:57 Error downloading Muzzy - Get Crazy / Feeling Stronger: FileNotFoundException: /mnt/3tbRED2/Monstercat/Muzzy - Get Crazy / Feeling Stronger.part/Muzzy - Get Crazy / Feeling Stronger.jpg.part (No such file or directory)

02:57:00 Error downloading Muzzy - Get Crazy / Feeling Stronger (The Remixes): FileNotFoundException: /mnt/3tbRED2/Monstercat/Muzzy - Get Crazy / Feeling Stronger (The Remixes).part/Muzzy - Get Crazy / Feeling Stronger (The Remixes).jpg.part (No such file or directory)

02:58:54 Error downloading Grabbitz - Ballin' / Don't Stop: FileNotFoundException: /mnt/3tbRED2/Monstercat/Grabbitz - Ballin' / Don't Stop.part/Grabbitz - Ballin' / Don't Stop.jpg.part (No such file or directory)

03:03:31 Error downloading Slippy - Restless / Vicimus: FileNotFoundException: /mnt/3tbRED2/Monstercat/Slippy - Restless / Vicimus.part/Slippy - Restless / Vicimus.jpg.part (No such file or directory)

03:03:31 Error downloading Au5 & Fractal - Ison / Pavonine: FileNotFoundException: /mnt/3tbRED2/Monstercat/Au5 & Fractal - Ison / Pavonine.part/Au5 & Fractal - Ison / Pavonine.jpg.part (No such file or directory)

03:18:17 Error downloading Hellberg feat. Aaron Richards - Synchronize (VIP Mix / Acoustic): FileNotFoundException: /mnt/3tbRED2/Monstercat/Hellberg feat. Aaron Richards - Synchronize (VIP Mix / Acoustic).part/Hellberg feat. Aaron Richards - Synchronize (VIP Mix / Acoustic).jpeg.part (No such file or directory)

03:51:11 Error downloading Protostar - SEQUENCE EP: FileNotFoundException: /mnt/3tbRED2/Monstercat/Protostar - SEQUENCE EP.part/Protostar - </init.seq>.flac.part (No such file or directory)
```

**Comment by Xerus2000** [comment] 2019-06-20 14:45
You are on Windows, right? Looks like I didn't parse the filenames correctly, let me see...

**Comment by Xerus2000** [comment] 2019-06-20 14:53
Please use the submit feedback function from the application, I need more details on this.

**Comment by defvs** [comment] 2019-06-20 21:39
1 - Doesn't seem on windows. His directory is UNIX `/mnt/*****/`

2 - It is because some of the files have '/' in them, and that messes with the filesystem. Example with `Slippy - Restless / Vicimus.jpg.part` that looks like a file named `Vicimus.jpg.part` in directory `Slippy - Restless `

**Comment by defvs** [comment] 2019-06-20 21:40
Easy way to fix it is to replace '\' in any filenames, including cover art. Will do it myself.

**Comment by defvs** [comment] 2019-06-20 21:42
Apparently it already is fixed using `replaceIllegalFileChar()` > Download.kt Line 127

**Comment by defvs** [comment] 2019-06-20 21:49
Can reproduce. As said earlier, issue is with albums containing illegal characters. But it is linked to **.part folders only.**

**Comment by defvs** [comment] 2019-06-20 22:07
I've got a fix folder-wise, for albums containing `/` on linux. `replaceIllegalFileChars` doesn't replace `/` on linux, only trims. This works with files, but not with folders, which need NO `/` AT ALL

**Comment by defvs** [comment] 2019-06-20 22:25
Fixed with #51

**Closed** 2019-06-21 13:21 UTC

**Comment by C0rn3j** [comment] 2019-06-21 14:26
@Xerus2000 how do I actually pull the fix? I've `git pull`'d the current monsterutilities repo but doing a ./gradlew run or build still errors out during the download.

```
16:23:40 Download started
16:24:18 Error downloading Muzzy - Get Crazy / Feeling Stronger: FileNotFoundException: /mnt/3tbRED2/MonstercatFLAC/Muzzy - Get Crazy / Feeling Stronger.part/Muzzy - Get Crazy / Feeling Stronger.jpg.part (No such file or directory)
```

**Comment by Xerus2000** [comment] 2019-06-21 14:43
I'll have to update the util version in the monsterutilities repo, give me a sec.
