### ISSUE TITLE
Songs newer than "Hush - Watervaal" cannot be played in the Player

### ISSUE THREAD

**Issue by defvs** [Xerus2000/monsterutilities#20] opened 2018-06-18 14:37 UTC

**Comment by Xerus2000** [comment] 2018-06-19 23:39
I am investigating and have already contacted Vindexus. He said that the MP3s in the blobs now contain less headers, apparently GStreamer thus fails to recognise the file.

**Comment by Xerus2000** [comment] 2018-06-21 12:41
The issue is resolved by updating to JDK 10. I'll elaborate on this in #22

**Comment by defvs** [comment] 2019-06-20 21:19
Fixed even on Java 8 ?

**Comment by Xerus2000** [comment] 2019-06-20 23:34
Oh really, looks like it. Maybe they fixed their files when they had their internal move ^^

**Closed** 2019-06-21 14:55 UTC
Labels: Player, bug
